### ISSUE TITLE
Enable prod.settings.php to be in repo

### ISSUE THREAD

**Issue by aleksijohansson** [wunderio/WunderTools#115]
Currently one of the most vital parts of a Drupal site configuration, the settings.php file, is not versioned in the repo but only manually managed in the servers like production. Find a way to manage also production settings.php securely in the repo.

**Comment by tharna** [comment]
This requires db credentials and any other sensitive information to be handled in some way. Environment variables would be one way, or we could also use provisioning to provision settings.php in place with correct environment specific variables.
We already have some settings passed as environment variables (e.g. wkv_site_env), but for sensitive information they can't be passed as plain variables as there is a risk to expose those too easily.
There is also some parts of the settings.php that are environment specific, but those could be handled by for example `switch`block utilizing the wkv_site_env variable.

**Comment by aleksijohansson** [comment]
@tharna Maybe just put the `prod.settings.php` in the repo without the db credentials and add an include statement in the `prod.settings.php` file to include the db credentials from a different file that is only present locally in the prod server?

**Comment by tharna** [comment]
I would really like to see only 1 settings.php used across the environments. But yes just including the credentials and other sensitive info could work. Then we could just provision that include file in place and store all the info in the ansible-vault.

**Comment by aleksijohansson** [comment]
1 settings.php across all environments would be even better! In local environment we could also have any required overrides in that separate include file.

**Comment by floretan** [comment]
settings.local.php is already commonly used for this purpose. It works for local development environments overrides and is already excluded from git. Putting that file in place in production would work.

**Comment by aleksijohansson** [comment]
Continuing from what @floretan said, we could just include all the configuration in one settings.php except for the database configuration and we could use the settings.local.php in production and other environments for providing the database configuration to the sites. I believe this requires some changes to how things are handled. In the build.sh world I think we have an environment prefixed settings.php which is put into place by build.sh. The future of build.sh should be considered here.

**Comment by tharna** [comment]
Wundermachina has branch for support of manually defined env vars for php process scope with php_env_vars dict. There is also a feature to automatically add drupal database credentials as env vars by defining php_env_vars_include_db. This will create two environment variable for each defined database in databases dict called DB_USER_[database_name] and DB_PASS_[database_name] which can be used in settings.php database configurations using getenv function.
https://github.com/wunderkraut/WunderMachina/tree/feature/PHPEnvVars

**Comment by tharna** [comment]
2 issues: 
1. if we have multiple environments on same server for the same project
2. Passing those vars to cli too would require exposing them on system level instead of just for the php-fpm process as it is now.

**Comment by badrange** [comment]
We're going to try out https://github.com/vlucas/phpdotenv - there are people that include the variables into settings.php, here: 

http://dev.itiden.se/2015/11/19/drupal-8-part-3-install-configure-develop-deploy/

**Comment by tharna** [comment]
That's a horrible option, no offense @badrange but:
- Instead of including one environment specific file you are depending on yet another 3rd party dependency that you need to install and maintain.
- Overhead from loading yet another class and running some variable parser and setting environment vars.
- Even the creator doesn't use this in prod, so you would need another solution for prod environments anyway.

I'll test some ways to expose those env vars to cli / drush without exposing them to the whole system. Or we could just expose those globally in the first place... just would like to play it as safe as possible.
For the multiple envs in same server we could use separate fpm confs for each environment, so variables with same name could be set for each environment separately.

**Comment by tharna** [comment]
Same env vars are now also added to /etc/drush/drushrc.php so they are available on drush / cli context. Only thing that needs to be resolved is the multiple environments on same server issue.

**Comment by tharna** [comment]
We won't be running multiple environments on same server so closing this for now as the original need for this request is solved.
Feel free to open separate issue for multiple environments on single server support if needed.
