### ISSUE TITLE
Install test runners with project composer.json

### ISSUE THREAD

**Issue by floretan** [wunderio/WunderTools#132]
Test runners like behat can be installed with the same composer.json as the project itself, they should just be added as dev-dependencies so these don't get installed on production environments.

**Comment by tharna** [comment]
Is there a way to install just the test runners? 
Separate tests allows us to run those tests in independent containers during CI, but I wouldn't like to install full application in such instances.

The testing process during deployment will be refined anyway, so this is something that we should keep in mind there. @onnimonni

**Comment by onnimonni** [comment]
`dev-dependencies` sounds still the right place for those packages.

I just need to make sure that the test runner server (php-fpm+nginx containers) install the packages like production would so we don't have parity issues.

**Comment by floretan** [comment]
This issue will probably be obsolete once https://github.com/wunderkraut/WunderTools/pull/173 is in. 

Regarding the possibility to run tests independently, the most valuable tests that we have in most projects are integration tests. Unit tests are useful for Drupal itself, but less for project work. That means that in pretty much every single project for which we have tests, these need to run on a deployed Drupal installation.

**Comment by tharna** [comment]
Closing this as #173 now implements this.
