### ISSUE TITLE
Test new site.yml configuration for dev/staging/prod

### ISSUE THREAD

**Issue by floretan** [wunderio/WunderTools#154]
The new site.yml configuration has only been tested locally, but not for dev/staging/production. Since we recommend that new projects use this as a base, we should check that the given configuration works as is.

**Comment by tharna** [comment]
Seems to be broken in many level. Need to figure out new deployment workflow to get it working. Also settings.php handling needs some love (see envvars issue)

**Comment by tharna** [comment]
#184 has working site.yml config for new sturcture and atomic build support.

**Comment by tharna** [comment]
There are working examples for each environment.
