### ISSUE TITLE
Stop using zip archive for starting a new client project

### ISSUE THREAD

**Issue by onnimonni** [wunderio/WunderTools#178]
Currently our docs tell people to download a zip archive of wundertools as a starter point. See more here:
https://github.com/wunderkraut/WunderTools/blob/master/docs/Setup.md

I think we should stop that and instead inherit straight from here.

This allows us to update any client project with:
```
$ git remote add upstream https://github.com/wunderkraut/WunderTools
$ git pull remote master
```

We can reduce the amount of history data by using shallow clones:
```
# Initial project start
$ git clone --depth 1 https://github.com/wunderkraut/WunderTools client-project

# Updating the project from this repository
$ git fetch upstream master:master --depth 1
```

Ofc this will sometimes result in annoying git conflicts but in the bigger picture this saves us countless of hours of manual update process.

**Comment by tharna** [comment]
Cloning the repo is default in the public documentation at http://wundertools.wunder.io project documentation templates should be updated accordingly or this kind of non-project specific info could be removed from there altogether so we don't duplicate information.
