### ISSUE TITLE
Env vars are only exposed to php-fpm and drush. Drupal console and codeception is not working out of the box.

### ISSUE THREAD

**Issue by guncha25** [wunderio/WunderTools#183]
There is issue with these getenv() functions in settings. Cli can not pick them up. In result drupal console is not usable and also codeception as they both bootstraps to drupal.

**Comment by tharna** [comment]
Simple solution would be to throw all the hard work we did for security out of the window and just expose those all to global env instead of restricting them to drush and php-fpm.
I tried to raise discussion about this when we implemented it in the first place, but nobody was interested :(

**Comment by tharna** [comment]
Moving the testing phase to travis makes this issue obsolete. Env variables already work for drupal and drush contexts.
