### ISSUE TITLE
Travis file inside of Drupal folder doesn't get executed

### ISSUE THREAD

**Issue by floretan** [wunderio/WunderTools#204]
Only the .travis.yml file in the project root gets executed. That leaves the following issues open:

- We are not testing that Wundertools works on an application level, to guarantee that new projects will just work.
- The process of using this repository as a template is a bit problematic, we don't want people to test Wundertools on every client project deployment.

**Comment by tharna** [comment]
There is only syntax check done on the main level .travis.yml so I think we could just use that to test the actual build too. 
There is a separate tests for the provisioning part on the wundermachina repo to not interfere with project work.
