### ISSUE TITLE
Make syncdb.sh work with D8

### ISSUE THREAD

**Issue by tharna** [wunderio/WunderTools#208]
Currently there are still e.g. drush commands that are only drupal 7 compatible.

**Comment by tharna** [comment]
There has been quite a lot of improvements made on the d7 branch. Would be nice to get those synced to master too. @aleksijohansson would you like to look into that?

**Comment by aleksijohansson** [comment]
I don't have a Drupal 8 project to work and test this on.

**Comment by aleksijohansson** [comment]
Got one now, assigning.
