### ISSUE TITLE
CHANGELOG is out of date

### ISSUE THREAD

**Issue by floretan** [wunderio/WunderTools#241]
There are many changes missing from the CHANGELOG file. Either we should update the file, or just remove it completely. 

Given that this file doesn't get updated for existing projects, it loses its purpose as soon as a project is created. I would suggest removing the file from the repository and adding a changelog to the documentation page.

**Comment by tharna** [comment]
We should definitely look ourself in the mirror overlooking the CHANGELOG updates. However the usefulness of it is debatable as I have seen people complaining "it's broken" and when I ask for the output I see they just have ignored the notice from changelog stating "your env will fail if you don't do this". 
Now hiding this info somewhere remote is probably even worse, so instead we should start educating the users to pay attention to the output.
Finally: CHANGELOG does get updated on the existing projects automatically.
