### ISSUE TITLE
drush syncdb command is not found in D8

### ISSUE THREAD

**Issue by Jancis** [wunderio/WunderTools#254]
I have enabled drush role, it seems to execute everything, but the command didn't work

```
[vagrant@local ~]$ cd /vagrant/drupal/web/
[vagrant@local web]$ which drush
/usr/lib/composer/vendor/bin/drush
[vagrant@local web]$ ls /usr/share/drush/commands/
syncdb.drush.inc
[vagrant@local web]$ drush cc drush
'drush' cache was cleared.                                           [success]
[vagrant@local web]$ drush syncdb
The drush command 'syncdb' could not be found.  Run `drush           [error]
cache-clear drush` to clear the commandfile cache if you have
installed new extensions.
```

I fixed that by installing syncdb in our web locally with `composer require juampynr/syncdb`.

I think it's because WT for D8 installation is installing drush via composer and `/usr/share/drush/commands/` is not scanned for drush commands at all.

**Comment by tharna** [comment]
Are you running drush 9? There are couple of other issues with that too, so currently recommended version of drush is still 8

**Comment by Jancis** [comment]
8.1.15
```
[vagrant@local web]$ drush --version
Drush Launcher Version: @git-version@
 Drush Version   :  8.1.15 

[vagrant@local web]$ which drush
/usr/lib/composer/vendor/bin/drush
```

**Comment by tharna** [comment]
Ok, then it probably just needs to be included in project composer.json.

**Comment by Jancis** [comment]
I think it needs addition for composer version of drush installation. Pretty sure the path for drush commands should be somewhere else to be picked up from global install.
but local is fine too, at least for me since i know how to fix it now.

**Comment by tharna** [comment]
This issue only concerns those projects using drush-launcher. Using globally installed drush this works, so for now the recommended way is to remove drush-launcher and install drush instead.
Default has been updated to use drush instead of drush-launcher.
