### ISSUE TITLE
Use pipenv and don't rebuild the virtualenv on every provision.sh run

### ISSUE THREAD

**Issue by aleksijohansson** [wunderio/WunderTools#286]
I noticed that provision.sh uses requirements.txt and rebuilds the virtualenv every time you run it. Please make provision.sh smarter (and faster) by using https://github.com/pypa/pipenv (can be easily installed with pip on every environment or even brew on macOS) instead to properly lock the versions and only rebuild if the required modules for the provisioning environment have changed.

**Comment by tharna** [comment]
resolved in feature/286-UsePipenv
