### ISSUE TITLE
Is this project deprecated? 

### ISSUE THREAD

**Issue by badrange** [wunderio/WunderTools#372]
If this is deprecated in favour of https://github.com/wunderio/drupal-project then a note in the README.md would be helpful for non-wunder-people!

**Comment by tormi** [comment]
Indeed, we don't use this project template in our new projects. Will add a note regarding this to the readme. Thanks for the feedback!

**Comment by tharna** [comment]
It is still being used in some legacy projects and there are also some use cases for this in new projects as well. So I wouldn't say it's yet deprecated, just not actively developed anymore.
Still, we should recommend using drupal-project instead by default :+1:

**Comment by tormi** [comment]
@tharna , feel free to adjust the wording in https://github.com/wunderio/WunderTools/commit/aad18f16952ca2a2c64bdfbac85082068ec18a61 ;)
